"""add CalendarEventMeetingNotes.archived

Revision ID: 8e192217487c
Revises: d6a18a67ae8b
Create Date: 2026-03-28 12:31:46.982005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e192217487c'
down_revision: Union[str, Sequence[str], None] = 'd6a18a67ae8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event_meeting_notes', sa.Column('archived', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_event_meeting_notes', 'archived')
    # ### end Alembic commands ###
