"""add title to notes

Revision ID: d6a18a67ae8b
Revises: b0ea8504c63f
Create Date: 2026-03-28 12:22:56.864976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a18a67ae8b'
down_revision: Union[str, Sequence[str], None] = 'b0ea8504c63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event_meeting_notes', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_event_meeting_notes', 'title')
    # ### end Alembic commands ###
