"""add notes_text and notes_markdown

Revision ID: b0ea8504c63f
Revises: 0d1783d269c3
Create Date: 2026-03-28 11:42:30.072997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ea8504c63f'
down_revision: Union[str, Sequence[str], None] = '0d1783d269c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event_meeting_notes', sa.Column('notes_text', sa.Text(), nullable=False))
    op.add_column('calendar_event_meeting_notes', sa.Column('notes_markdown', sa.Text(), nullable=True))
    op.drop_column('calendar_event_meeting_notes', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event_meeting_notes', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('calendar_event_meeting_notes', 'notes_markdown')
    op.drop_column('calendar_event_meeting_notes', 'notes_text')
    # ### end Alembic commands ###
