"""add meeting notes table

Revision ID: cf453af874ef
Revises: cd313bc67ae8
Create Date: 2026-03-28 09:44:03.974300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf453af874ef'
down_revision: Union[str, Sequence[str], None] = 'cd313bc67ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_event_meeting_notes',
    sa.Column('calendar_event_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('GRANOLA', name='meetingnotessource'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_event_meeting_notes_note_id'), 'calendar_event_meeting_notes', ['note_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_event_meeting_notes_note_id'), table_name='calendar_event_meeting_notes')
    op.drop_table('calendar_event_meeting_notes')
    sa.Enum('GRANOLA', name='meetingnotessource').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
